# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrant OpenCrowbar

props = JSON.load(IO.read('personal.json'))

Vagrant.configure("2") do |config|

  config.vm.define props['guest_hostname'] do |cb2dev|

    cb2dev.vm.hostname = "#{props['guest_hostname']}" 
    cb2dev.vm.box = "#{props['box_name']}" 
    cb2dev.vm.box_url = "#{props['box_url']}" 
    cb2dev.vm.synced_folder props['synced_dir_host'], props['synced_dir_guest']
    cb2dev.vm.network "private_network", ip: "192.168.124.10"

    #cb2dev.vm.synced_folder props['cache_dir_host'], props['cache_dir_guest']

    cb2dev.vm.provider :virtualbox do |vb|
      vb.gui  = true
      vb.name = "#{props['guest_hostname']}"
      vb.customize ["modifyvm", :id, "--cpus", props['guest_cpus']]
      vb.customize ["modifyvm", :id, "--memory", props['guest_ram']]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#     config.vm.network "private_network", ip: "192.168.124.2", virtualbox__intnet: "vboxnet0"
      # cool stuff!
      # install the plugin:  vagrant plugin install vagrant-vbguest 
      #config.vbguest.auto_update = false #true by default when plugin installed
    end

    cb2dev.vm.provision :chef_solo do |chef|
      #chef.attempts = 10
      chef.json = { :props => props }
      chef.cookbooks_path = "chef/cookbooks"
      chef.roles_path = "chef/roles"
      chef.data_bags_path = "chef/data_bags"
      chef.log_level = ENV.fetch("CHEF_LOG", "debug").downcase.to_sym

      # recipes and cookbooks
      chef.add_recipe "cb2::create-user"
      chef.add_recipe "cb2::http-proxy-client"
      chef.add_recipe "cb2::package-repo"
      chef.add_recipe "cb2::ruby"
#      chef.add_recipe "cb2::gems"
      chef.add_recipe "cb2::chef-tools"
      chef.add_recipe "cb2::docker"
      chef.add_recipe "cb2::crowbar-1-source-and-build-prep"
      chef.add_recipe "cb2::crowbar-4-test-deps"
#      chef.add_recipe "cb2::crowbar-5-setup-cache"
      chef.add_recipe "cb2::postgresql"
      chef.add_recipe "cb2::vim-setup"
      chef.add_recipe "cb2::sshfs"
    end
  end
end
